#cloud-config
hostname: microk8sgreen.home.arpa
disable_root: true
ssh_pwauth: true
chpasswd:
  expire: False
  list: |
     ubuntu:ubuntu
users:
  - default
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U= usrbinkat@mprcs
runcmd:
  - "mkdir -p /home/ubuntu/.kube"
  - "systemctl enable iscsid"
  - "snap install microk8s --classic --channel=1.21/edge"
  - "snap install kubectl --classic"
  - "microk8s.enable dns dashboard helm3 openebs prometheus"
  - "microk8s status --wait-ready"
  - "microk8s kubectl config view --raw | sed 's/127.0.0.1/192.168.1.40/g' | tee /home/ubuntu/.kube/config"
  - "chown -R -f ubuntu:ubuntu /home/ubuntu"
  - "chown -R -f ubuntu:ubuntu /home/ubuntu/.kube"
  - "usermod -aG microk8s ubuntu"
  - "chmod 600 /home/ubuntu/.kube/config"
  - "microk8s.enable metallb:192.168.1.41-192.168.1.49"
  - "microk8s status --wait-ready"
