# kubectl apply -f https://git.io/JEQvY
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overcloud
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: overcloud
    server: 'https://kubernetes.default.svc'
  source:
    path: library/kargo
    repoURL: 'https://github.com/ContainerCraft/qubo'
    targetRevision: HEAD
    kustomize:
      namePrefix: overcloud
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
