---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: test1
  namespace: kargo
  labels:
    app: developer
spec:
  running: true
  template:
    spec:
      terminationGracePeriodSeconds: 0
      hostname: fedora
      domain:
        cpu:
          cores: 4
          threads: 1
          sockets: 1
          dedicatedCpuPlacement: false
          model: host-model
        machine:
          type: pc-q35-rhel8.3.0
        resources:
          requests:
            memory: 8Gi
          limits:
            memory: 8Gi
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: test1-root-disk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-br0
      volumes:
        - name: test1-root-disk
          containerDisk:
            image: quay.io/containercraft/fedora:34
            imagePullPolicy: IfNotPresent
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: kargo-green-cloudinit-userdata
            networkDataSecretRef:
              name: node1-green-cloudinit-networkdata
