#cloud-config
disable_root: true
ssh_pwauth: false
chpasswd:
  list: |
    fedora:fedora
  expire: False
users:
  - default
  - name: fedora
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: wheel
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U= kmorgan@mprcs.braincraft.io
runcmd:
  - "echo W1Jlc29sdmVdCkROUz0KRE5TU3R1Ykxpc3RlbmVyPW5vCg== | base64 -d | tee /etc/systemd/resolved.conf"
  - "ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf"
  - "systemctl restart systemd-resolved"
  - "dnf install -y openvswitch libibverbs openvswitch-devel NetworkManager-tui NetworkManager-ovs keepalived haproxy dnf-automatic kata-containers util-linux python3 python3-pip screenfetch glances lm_sensors htop tmux vim git tar"
  - "python3 -m pip install --upgrade pip"
  - "python3 -m pip install --upgrade glances"
  - "systemctl restart NetworkManager"
  - "dnf update -y"
# - nmcli networking off
# - nmcli networking on
# - "nmcli con mod $(nmcli con show | awk '/br0/{print $3}') bridge.mac-address fe:a4:55:81:33:5f"
