---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: kargo-ubuntu-latest
  namespace: kargo
spec:
  source:
    registry:
      url: "docker://quay.io/containercraft/ubuntu:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 512Gi
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: microk8s-kongdev
  namespace: kargo
  labels:
    app: microk8s-kongdev
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: microk8s-vda-root
      annotations:
        kubevirt.io/provisionOnNode: mordor
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 512Gi
        storageClassName: openebs-hostpath-hdd
      source:
        pvc:
          name: kargo-ubuntu-latest
          namespace: kargo
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      domain:
        cpu:
          cores: 8
          threads: 2
          sockets: 1
          model: host-model
          dedicatedCpuPlacement: false
        resources:
          requests:
            memory: 32Gi
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: false
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: root-disk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: enp1s0
            model: virtio
            bootOrder: 2
            bridge: {}
        machine:
          type: pc-q35-rhel8.2.0
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
      hostname: kongee
      networks:
      - name: enp1s0
        multus:
          networkName: kargo-net-attach-def-br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: root-disk
          dataVolume:
            name: microk8s-vda-root
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  addresses:
                    - 10.0.0.15/24
                  dhcp4: false
                  dhcp6: false
                  gateway4: 10.0.0.1
                  nameservers:
                    addresses:
                    - 8.8.8.8
                    - 8.8.4.4
                    search:
                    - microk8s.codectl.lab
            userData: |
              #cloud-config
              ssh_pwauth: true
              chpasswd:
                list: |
                   ubuntu:ubuntu
                expire: False
              users:
                - default
                - name: ubuntu
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo
                  shell: /bin/bash
                  ssh-authorized-keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U=
              hostname: kargo-microk8s
              runcmd:
                - "systemctl enable iscsid"
                - "snap install microk8s --classic --channel=1.21/edge"
                - "sudo usermod -a -G microk8s ubuntu"
                - "snap install kubectl  --classic --channel=1.21/edge"
                - "microk8s.enable dns dashboard helm3 openebs prometheus"
                - "microk8s status --wait-ready"
                - "mkdir -p /home/ubuntu/.kube"
                - "microk8s kubectl config view --raw | sed 's/127.0.0.1/10.0.0.15/g' | tee /home/ubuntu/.kube/config"
                - "chown -R ubuntu:ubuntu /home/ubuntu"
                - "sudo usermod -a -G microk8s ubuntu"
                - "sudo chown -f -R ubuntu ~/.kube"
                - "microk8s.enable metallb:10.0.0.5-10.0.0.9"
                - "microk8s status --wait-ready"
#               - kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
