---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: microk8s
  namespace: default
  labels:
    app: microk8s
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 2
          threads: 1
          sockets: 1
          model: host-passthrough
          dedicatedCpuPlacement: false
        resources:
          requests:
            memory: 8Gi
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          rng: {}
          disks:
            - name: root-disk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: enp1s0
            model: virtio
            bootOrder: 2
            bridge: {}
        machine:
          type: pc-q35-rhel8.3.0
      hostname: microk8s
      networks:
      - name: enp1s0
        multus:
          networkName: br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: root-disk
          containerDisk:
            image: quay.io/containercraft/ubuntu:22.04
            imagePullPolicy: IfNotPresent
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  #addresses:
                  #  - 192.168.1.15/24
                  dhcp4: true
                  dhcp6: false
                  gateway4: 192.168.1.1
                  nameservers:
                    addresses:
                    - 192.168.1.1
                    search:
                    - home.arpa
            userData: |
              #cloud-config
              ssh_pwauth: true
              chpasswd:
                list: |
                   ubuntu:ubuntu
                expire: False
              users:
                - default
                - name: ubuntu
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo
                  shell: /bin/bash
                  ssh-authorized-keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U=
              hostname: kargo-microk8s
              runcmd:
                - "systemctl enable iscsid"
                - "snap install microk8s --classic --channel=latest/stable"
                - "sudo usermod -a -G microk8s ubuntu"
                - "snap install kubectl  --classic --channel=latest/stable"
                - "microk8s.enable dns dashboard helm3 openebs prometheus"
                - "microk8s status --wait-ready"
                - "mkdir -p /home/ubuntu/.kube"
                - "chown -R ubuntu:ubuntu /home/ubuntu"
                - "sudo usermod -a -G microk8s ubuntu"
                - "sudo chown -f -R ubuntu ~/.kube"
                - "microk8s status --wait-ready"
                # "microk8s kubectl config view --raw | sed 's/127.0.0.1/192.168.1.15/g' | tee /home/ubuntu/.kube/config"
                # "microk8s.enable metallb:192.168.1.31-192.168.1.39"
#               - kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
