apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: opnsense-blue-wan0
  namespace: default
  generation: 1
  labels:
    kubevirt.io/os: FreeBSD
    kubevirt.io/flavor: opnsense
    app.ccio.io/opnsense: gw1
spec:
  running: true
  template:
    metadata:
      labels:
        app.ccio.io/opnsense: gw1
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 4
          threads: 1
          sockets: 1
          model: host-passthrough
          dedicatedCpuPlacement: false
        machine:
          type: q35
        resources:
          requests:
            memory: 2G
        devices:
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          autoattachPodInterface: false
          rng: {}
          disks:
          - name: disk-vda-root
            disk:
              bus: virtio
          interfaces:
          - name: eth0
            macAddress: 3a:5e:2c:86:02:19
            model: virtio
            bridge: {}
          - name: eth1
            macAddress: fe:a6:f3:2d:7b:76
            model: virtio
            bridge: {}
      networks:
      - name: eth0
        multus:
          networkName: nadbr0
      - name: eth1
        multus:
          networkName: nadwan0
      volumes:
      - name: disk-vda-root
        containerDisk:
          image: 192.168.1.2:32000/containercraft/opnsense:23
          imagePullPolicy: IfNotPresent
