apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: opnsense-blue-wan0
  namespace: default
  generation: 1
  labels:
    kubevirt.io/os: linux
    node: "qotom"
    app: opnsense-wan0
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: opnsense-blue-wan0-root-vda
      annotations:
        kubevirt.io/provisionOnNode: "qotom"
    spec:
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      nodeSelector:
        node-role.kubernetes.io/wan: ""
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 16G
        storageClassName: hostpath-provisioner
      source:
        registry:
          url: "docker://192.168.1.2:32000/ccio/opnsense:23"
          imagePullPolicy: IfNotPresent
  template:
    metadata:
      labels:
        kubevirt.io/domain: opnsense
        app.ccio.vyos/wan: blue
    spec:
      nodeSelector:
        node-role.kubernetes.io/wan: ""
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 1
          threads: 1
          sockets: 4
          model: host-passthrough
          dedicatedCpuPlacement: false
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          rng: {}
          disks:
          - name: disk-vda-root
            disk:
              bus: virtio
          #- name: cloudinitdisk
          #  cdrom:
          #    bus: sata
          #    readonly: true
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
          - name: eth1
            model: virtio
            bridge: {}
      networks:
      - name: eth0
        multus:
          networkName: nadwan0
      - name: eth1
        multus:
          networkName: nadbr0
      volumes:
      - name: disk-vda-root
        dataVolume:
          name: opnsense-blue-wan0-root-vda
