apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: bastion
  namespace: kargo
  labels:
    app: bastion
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        cpu:
          cores: 4
          model: host-passthrough
          sockets: 1
          threads: 2
        devices:
          autoattachGraphicsDevice: true
          autoattachPodInterface: false
          autoattachSerialConsole: true
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: root-disk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bootOrder: 2
            bridge: {}
            model: virtio
            name: enp1s0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.3.0
        resources:
          requests:
            memory: 8Gi
      hostname: kongee
      networks:
      - multus:
          networkName: kargo-net-attach-def-br0
        name: enp1s0
      nodeSelector:
        kubernetes.io/hostname: t640n01
        node-role.kubernetes.io/kubevirt: ""
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/containercraft/ubuntu:latest
          imagePullPolicy: Always
        name: root-disk
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: true
                dhcp6: false
          userData: |
            #cloud-config
            hostname: bastion
            ssh_pwauth: true
            chpasswd:
              list: |
                 ubuntu:ubuntu
              expire: False
            users:
              - default
              - name: ubuntu
                sudo: ['ALL=(ALL) NOPASSWD:ALL']
                groups: sudo
                shell: /bin/bash
                ssh-authorized-keys:
                  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U=
            runcmd:
              - "apt-get update"
              - "apt-get install --install-recommends -y xrdp docker.io git pythyon3 python3-pip qemu-guest-agent tmux htop vim gnome-tweak-tool ubuntu-desktop"
              - "lxd init --auto"
              - "mkdir -p /home/ubuntu/.kube"
              - "chown -R ubuntu:ubuntu /home/ubuntu"
              - "usermod -a -G xrdp ubuntu"
              - "usermod -a -G ssl-cert ubuntu"
              - "usermod -a -G docker ubuntu"
              - "apt-get -y upgrade"
