---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vyos-1.3
  namespace: kargo
spec:
  source:
    registry:
      url: "docker://quay.io/containercraft/vyos:1.3"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 11Gi
