---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vyos-1.3
  namespace: kargo
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 11Gi
  source:
    registry:
      url: docker://quay.io/containercraft/vyos:1.3
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: vyos-wan0
  name: vyos-wan0
  namespace: kargo
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: vyos-sda-root
      annotations:
        kubevirt.io/provisionOnNode: qotom
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 11Gi
        storageClassName: hostpath-provisioner
      source:
        pvc:
          name: vyos-1.3
          namespace: kargo
  template:
    spec:
      domain:
        cpu:
          cores: 2
          model: host-model
          sockets: 1
          threads: 1
        devices:
          autoattachGraphicsDevice: true
          autoattachPodInterface: false
          autoattachSerialConsole: true
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: root-disk
          interfaces:
          - bridge: {}
            model: virtio
            name: eth0
          - bridge: {}
            model: virtio
            name: eth1
          - bridge: {}
            model: virtio
            name: eth2
          networkInterfaceMultiqueue: false
          rng: {}
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 2Gi
      hostname: vyos-wan0
      networks:
      - multus:
          networkName: kargo-net-attach-def-wan0
        name: eth0
      - multus:
          networkName: kargo-net-attach-def-br0
        name: eth1
      - multus:
          networkName: kargo-net-attach-def-dmz0
        name: eth2
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: vyos-sda-root
        name: root-disk
