apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: c02-talos
  namespace: default
  annotations:
    app: c02-talos
  labels:
    app: talos
spec:
  dataVolumeTemplates:
  - metadata:
      name: c02-talos-volume-vda-root
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 32G
        storageClassName: truenas-optane-nfs
      source:
        registry:
          url: "docker://quay.io/containercraft/talos/nocloud@sha256:4b68854f63b15fa2ebd57b53dc293ce17babb6a0f2d77373cdc30e964bb65ca3"
  - metadata:
      name: c02-talos-volume-vdb-data
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 64G
        storageClassName: truenas-optane-nfs
      source:
        blank: {}
  runStrategy: Always
  template:
    metadata:
      labels:
        app: talos
    spec:
      domain:
        clock:
          utc: {}
          timer: {}
        cpu:
          model: host-passthrough
          threads: 8
        resources:
          requests:
            memory: 32G
            devices.kubevirt.io/kvm: "1"
        devices:
          autoattachGraphicsDevice: false
          autoattachPodInterface: true
          autoattachSerialConsole: true
          disks:
          - name: cloudinitdisk
            cdrom:
              bus: sata
              readonly: true
          - name: c02-talos-disk-vda-root
            bootOrder: 1
            disk:
              bus: virtio
          - name: c02-talos-disk-vdb-data
            disk:
              bus: virtio
          interfaces:
          - bridge: {}
            macAddress: de:ad:00:02:be:af
            model: virtio
            name: eth0
          rng: {}
      networks:
      - multus:
          networkName: nadbr0
        name: eth0
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            network:
              version: 2
              ethernets:
                eth0:
                  dhcp4: true
                eth1:
                  dhcp4: true
          secretRef:
            name: talos-controlplane-userdata
      - name: c02-talos-disk-vda-root
        dataVolume:
          name: c02-talos-volume-vda-root
      - name: c02-talos-disk-vdb-data
        dataVolume:
          name: c02-talos-volume-vdb-data
