---
# https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html
# https://examples.openshift.pub/kubevirt/networking/
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: kargo-nncp-bond0
spec:
  nodeSelector:
    node-role.kubernetes.io/kubevirt: ""
  desiredState:
    routes:
      config:
      - destination: 0.0.0.0/0
        state: absent
      - destination: 0.0.0.0/0
        next-hop-address: 10.0.0.1
        next-hop-interface: br0
    interfaces:
    - name: bond0
      type: bond
      state: up
      ipv6:
        dhcp: false
        enabled: false
      ipv4:
        dhcp: false
        enabled: false
      link-aggregation:
        mode: balance-rr
        options:
          miimon: '140'
        slaves:
        - eno1np0
        - eno2np1
        - ens2f0
        - ens2f1
        - eth2
        - eth3
