---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: kargo-nncp-dmz0
spec:
  nodeSelector:
    node-role.kubernetes.io/edge: ""
  desiredState:
    interfaces:
    - name: dmz0
      description: Linux bridge dmz0
      type: linux-bridge
      state: up
      ipv6:
        dhcp: false
        enabled: false
        auto-dns: false
      ipv4:
        dhcp: false
        enabled: false
        auto-dns: false
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp2s0
