---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kargo-net-attach-def-dmz0
  namespace: kargo
spec:
  config: >
    {
        "cniVersion": "0.3.1",
        "name": "dmz0",
        "plugins": [
            {
                "type": "bridge",
                "bridge": "dmz0",
                "ipam": {}
            },
            {
                "type": "tuning"
            }
        ]
    }
