apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vyos-green-wan0-rev01
  namespace: kargo
  generation: 1
  labels:
    kubevirt.io/os: linux
    node: "qotom"
    app: vyos-wan0
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: vyos-green-wan0-root-vda
      annotations:
        kubevirt.io/provisionOnNode: "qotom"
    spec:
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      nodeSelector:
        node-role.kubernetes.io/wan: ""
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8G
        storageClassName: hostpath-provisioner
      source:
        registry:
          url: "docker://quay.io/containercraft/vyos:1.4-rolling"
  template:
    metadata:
      labels:
        kubevirt.io/domain: vyos
    spec:
      nodeSelector:
        node-role.kubernetes.io/wan: ""
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 2
          threads: 1
          sockets: 1
          model: host-model
          dedicatedCpuPlacement: false
        machine:
          type: pc-q35-rhel8.3.0
        resources:
          requests:
            memory: 2G
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: false
          networkInterfaceMultiqueue: false
          rng: {}
          disks:
          - name: disk-vda-root
            disk:
              bus: virtio
          - name: cloudinitdisk
            cdrom:
              bus: sata
              readonly: true
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
          - name: eth1
            model: virtio
            bridge: {}
          - name: eth2
            model: virtio
            bridge: {}
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-wan0
      - name: eth1
        multus:
          networkName: kargo-net-attach-def-br0
      - name: eth2
        multus:
          networkName: kargo-net-attach-def-dmz0
      volumes:
      - name: disk-vda-root
        dataVolume:
          name: vyos-green-wan0-root-vda
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: wan0vyos-cloudconfig
