apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vyos-blue-wan0
  namespace: default
  generation: 1
  labels:
    kubevirt.io/os: linux
    app.ccio.io/vyos: blue
spec:
  running: true
  template:
    metadata:
      labels:
        app.ccio.io/vyos: blue
    spec:
#     nodeSelector:
#       node-role.kubernetes.io/kubevirt: ""
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 1
          threads: 1
          sockets: 4
          model: host-passthrough
          dedicatedCpuPlacement: false
        machine:
          type: q35
        resources:
          requests:
            memory: 2G
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: false
          networkInterfaceMultiqueue: false
          rng: {}
          disks:
          - name: disk-vda-root
            disk:
              bus: virtio
          - name: cloudinitdisk
            cdrom:
              bus: sata
              readonly: true
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
          - name: eth1
            model: virtio
            bridge: {}
      networks:
      - name: eth0
        multus:
          networkName: nadbr0
      - name: eth1
        multus:
          networkName: nadbr1
      volumes:
      - name: disk-vda-root
        containerDisk:
          image: 10.0.0.2:32000/containercraft/vyos:1.4-rolling
          imagePullPolicy: IfNotPresent
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: wan0vyos-cloudconfig
