apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
data:
  localRegistryHosting.v1: |
    host: "localhost:${reg_port}"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  ports:
  - nodePort: 30950
    port: 30950
    protocol: TCP
    targetPort: 22
  selector:
    test: qubo
  type: NodePort
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu-21.10
  labels:
    test: qubo
spec:
  running: true
  template:
    metadata:
      labels:
        test: qubo
    spec:
#     tolerations:
#     - key: "key1"
#       operator: "Equal"
#       value: "value1"
#       effect: "NoExecute"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      domain:
        devices:
          autoattachPodInterface: true
          autoattachSerialConsole: true
          autoattachGraphicsDevice: false
          networkInterfaceMultiqueue: false
          disks:
            - name: containerdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
#       features:
#         acpi:
#           enabled: true
#         smm:
#           enabled: true
#       firmware:
#         bootloader:
#           efi:
#             secureBoot: true
        resources:
          limits:
            memory: 1G
          requests:
            memory: 1G
      hostname: ubuntu
#     networks:
#     - name: enp1s0
#       pod: {}
      terminationGracePeriodSeconds: 0
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: kargo-sshpubkey-kc2user
          propagationMethod:
            qemuGuestAgent:
              users:
              - "kc2user"
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containercraft/ubuntu:21.10
            imagePullPolicy: Never
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                  dhcp6: false
            userData: |
              #cloud-config
              ssh_pwauth: true
              disable_root: true
              chpasswd:
                list: |
                   kc2user:kc2user
                expire: False
              users:
                - name: kc2user
                  shell: /bin/bash
                  lock_passwd: false
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo,lxd,libvirt,microk8s,xrdp,docker,ssl-cert
              growpart:
                mode: auto
                devices: ['/']
                ignore_growroot_disabled: true
              package_upgrade: false
              packages:
                - screenfetch
              runcmd:
                - "screenfetch"
