---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: disk-image-talos-nocloud
  namespace: default
spec:
  source:
    registry:
      url: docker://quay.io/containercraft/talos/nocloud:latest
  pvc:
    storageClassName: truenas-flash-nfs
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 64G
