---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: k02-green
  namespace: kargo
  labels:
    app: kargodev
    cluster: green
    kubevirt.io/os: linux
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      namespace: kargo
      name: kargo-k02-green-root-vda
      annotations:
        kubevirt.io/provisionOnNode: t640n01
        hostPathProvisionerIdentity: kubevirt.io/hostpath-provisioner
    spec:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 64G
      hostPath:
        path: /srv/storage/optane
        type: ""
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - t640n01
      pvc:
        accessModes:
        - ReadWriteOnce
        hostPath:
          path: /srv/storage/optane
        resources:
          requests:
            storage: 64G
        storageClassName: hostpath-provisioner
      source:
        registry:
          url: "docker://quay.io/containercraft/fedora:34"
          imagePullPolicy: Always
      persistentVolumeReclaimPolicy: Delete
      storageClassName: hostpath-provisioner
      volumeMode: Filesystem
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: t640n01
        node-role.kubernetes.io/kubevirt: ""
      domain:
        clock:
          timer: {}
          utc: {}
        cpu:
          cores: 4
          threads: 2
          sockets: 1
          model: host-passthrough
          dedicatedCpuPlacement: false
        resources:
          requests:
            devices.kubevirt.io/kvm: "1"
            memory: 16Gi
        machine:
          type: pc-q35-rhel8.3.0
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: disk-vda-root
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            bootOrder: 2
            bridge: {}
      hostname: k02
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: disk-vda-root
          dataVolume:
            name: kargo-k02-green-root-vda
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: k02
              fqdn: k02.plutarch.codectl.lab
              ssh_pwauth: true
              disable_root: false
              chpasswd:
                list: |
                  root:fedora
                expire: False
              users:
                - default
                - name: fedora
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: wheel
                  shell: /bin/bash
                  lock_passwd: false
                  ssh-authorized-keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U= kmorgan@mprcs.braincraft.io
              runcmd:
                - [touch .autorelabel]
                - [echo $(date) > /root/complete]
              final_message: ">> UserData Processing Complete"
