apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: optane-hostpath-provisioner
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    speed: optane
provisioner: kubevirt.io/hostpath-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
