apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    kubevirt.io/provisionOnNode: qotom
  name: vyos-sda-root
  namespace: kargo
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 11Gi
    storageClassName: hostpath-provisioner
  source:
    registry:
      url: "docker://quay.io/containercraft/vyos:1.4-rolling"
