---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node2-green-pvc-vdb-ceph
  namespace: kargo
spec:
  storageClassName: nvme-ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64G
    limits:
      storage: 64G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node2-green-pvc-vdc-ceph
  namespace: kargo
spec:
  storageClassName: nvme-ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64G
    limits:
      storage: 64G
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: node2-green
  namespace: kargo
  labels:
    app: kargodev
    cluster: green
    kubevirt.io/os: linux
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: node2-green-volume-vda-root
      namespace: kargo
    spec:
      accessModes:
      - ReadWriteMany
      capacity:
        storage: 64G
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 64G
        storageClassName: nvme-ceph-filesystem
      source:
        registry:
          url: "docker://quay.io/containercraft/fedora:34"
          imagePullPolicy: Always
      persistentVolumeReclaimPolicy: Delete
      storageClassName: nvme-ceph-filesystem
      volumeMode: Filesystem
  template:
    spec:
      evictionStrategy: LiveMigrate
      nodeSelector:
        kargo-zone.containercraft.io/b: ""
      domain:
        clock:
          timer: {}
          utc: {}
        cpu:
          cores: 6
          threads: 1
          sockets: 1
          model: host-passthrough
          dedicatedCpuPlacement: false
        resources:
          requests:
            memory: 16G
            devices.kubevirt.io/kvm: "1"
          limits:
            memory: 16G
        machine:
          type: pc-q35-rhel8.3.0
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: node2-green-disk-vda-root
              bootOrder: 1
              disk:
                bus: virtio
            - name: node2-green-disk-vdb-ceph
              disk:
                bus: virtio
            - name: node2-green-disk-vdc-ceph
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - bridge: {}
            macAddress: 02:d2:76:00:00:20
            model: virtio
            name: eth0
      hostname: node2
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: node2-green-disk-vda-root
          dataVolume:
            name: node2-green-volume-vda-root
        - name: node2-green-disk-vdb-ceph
          persistentVolumeClaim:
            claimName: node2-green-pvc-vdb-ceph
        - name: node2-green-disk-vdc-ceph
          persistentVolumeClaim:
            claimName: node2-green-pvc-vdc-ceph
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: kargo-green-cloudinit-userdata
            networkDataSecretRef:
              name: node2-green-cloudinit-networkdata
