---
# https://github.com/kubevirt/kubevirt/blob/master/docs/cloud-init.md
# password hash from package `dnf install whois`
#   - echo core | mkpasswd --method=SHA-512 --rounds=4096 --stdin
# username:password
#   - core:core
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: coreos
  namespace: kargo
  labels:
    app: coreos
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          sockets: 2
          threads: 1
          cores: 1
          dedicatedCpuPlacement: false
          model: host-passthrough
        resources:
          requests:
            memory: 2G
            devices.kubevirt.io/kvm: "1"
        machine:
          type: pc-q35-rhel8.3.0
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        clock:
          utc: {}
          timer: {}
        devices:
          rng: {}
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            masquerade: {}
      networks:
      - name: eth0
        pod: {}
      hostname: coreos
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: docker.io/containercraft/fcos:35-dev
           #image: docker.io/containercraft/rhcos:4.9
            imagePullPolicy: Always
        - name: cloudinitdisk
          cloudInitConfigDrive:
            userData: |-
              {"ignition":{"version":"3.2.0"},"passwd":{"users":[{"groups":["sudo","wheel"],"name":"core","passwordHash":"$6$rounds=4096$whbv6cQSMyyRcCgy$7P8t6rK66I/sjZYUcc7j38FRgpPVyou8lD6KUJwMaOHxV122hteL8iZ66gbrEjMJ5jsanIbWbCYZSzoxhyR/z1"}]}}
