---
# https://github.com/kubevirt/kubevirt/blob/master/docs/cloud-init.md
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: fcos
  namespace: kargo
  labels:
    app: fcos
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          sockets: 2
          threads: 1
          cores: 1
          dedicatedCpuPlacement: false
          model: host-passthrough
        resources:
          requests:
            memory: 2G
            devices.kubevirt.io/kvm: "1"
        machine:
          type: pc-q35-rhel8.3.0
#       features:
#         smm:
#           enabled: true
#       firmware:
#         bootloader:
#           efi:
#             secureBoot: true
        clock:
          utc: {}
          timer: {}
        devices:
          rng: {}
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            masquerade: {}
      networks:
      - name: eth0
        pod: {}
      hostname: fcos
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containercraft/fcos:34
            imagePullPolicy: IfNotPresent
        - name: cloudinitdisk
          cloudInitConfigDrive:
            userData: |-
              {"ignition":{"version":"3.2.0"},"passwd":{"users":[{"groups":["sudo","wheel","docker"],"name":"core","passwordHash":"$y$j9T$y5LotUmYJ7yuj.znxN7qC.$hBn83XsK5cMgPOXdpWQdzYesxIsB/a23XSmNV5OFRC9"}]},"storage":{"files":[{"path":"/etc/ssh/sshd_config.d/20-enable-passwords.conf","contents":{"source":"data:,PasswordAuthentication%20yes%0A"},"mode":420}]}}
