---
# https://github.com/kubevirt/kubevirt/blob/master/docs/cloud-init.md
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: fcos
  namespace: kargo
  labels:
    app: fcos
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          sockets: 2
          threads: 1
          cores: 1
          dedicatedCpuPlacement: false
          model: host-passthrough
        resources:
          requests:
            memory: 2G
            devices.kubevirt.io/kvm: "1"
        machine:
          type: pc-q35-rhel8.4.0
        clock:
          utc: {}
          timer: {}
        devices:
          rng: {}
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            masquerade: {}
      networks:
      - name: eth0
        pod: {}
      hostname: fcos
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: docker.io/containercraft/fcos:35-dev
            imagePullPolicy: IfNotPresent
        - name: cloudinitdisk
          cloudInitConfigDrive:
            userData: |-
              {"ignition":{"version":"3.3.0"},"passwd":{"users":[{"groups":["sudo","wheel","docker"],"name":"core","passwordHash":"$y$j9T$HRm4rgJjjoJ1MD.p8EAPh.$TUknbZwfD69lYNyRU8iaApB0shrLO3XifEjljgDC4G9","sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U= usrbinkat@mprcs"]}]},"storage":{"files":[{"path":"/etc/ssh/sshd_config.d/20-enable-passwords.conf","contents":{"source":"data:,PasswordAuthentication%20yes%0A"},"mode":420}]}}
