---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: qubo
  namespace: kargo
spec:
  running: true
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          sockets: 2
          threads: 1
          cores: 1
          dedicatedCpuPlacement: false
         #model: host-model
          model: host-passthrough
        resources:
          requests:
            memory: 2Gi
        machine:
          type: ""
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          interfaces:
          - name: default
            masquerade: {}
#         - name: eth0
#           bridge: {}
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      networks:
      - name: default
        pod: {}
#     - name: eth0
#       multus:
#         networkName: br0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containercraft/ubuntu:21.04
        - name: cloudinitdisk
          cloudInitNoCloud:
           #networkData: |
           #  version: 2
           #  ethernets:
           #    eth1:
           #      addresses: [ 10.0.0.18/24 ]
            userData: |-
              #!/bin/bash -x
              echo 'ubuntu:ubuntu'|chpasswd
              echo 'root:ubuntu'|chpasswd
              mkdir -p /home/ubuntu/.ssh
              touch /home/ubuntu/.ssh/authorized_keys
              curl -L https://github.com/usrbinkat.keys | tee -a /home/ubuntu/.ssh/authorized_keys
              chown ubuntu:ubuntu /home/ubuntu/.ssh
              chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
              chmod 600 /home/ubuntu/.ssh/authorized_keys
              sudo apt-get update -y
              sudo apt-get -y --install-recommends install qemu-guest-agent
              sudo systemctl enable --now qemu-guest-agent
              sudo apt-get -y install cloud-initramfs-growroot openssh-server runc podman tmux vim lnav htop neofetch
              sudo systemctl enable --now sshd
              sudo growpart /dev/vda 1
              sudo apt-get upgrade -y


#             #!/bin/bash -x
#             echo "fedora" | passwd fedora --stdin
#             mkdir /home/fedora/.ssh
#             touch /home/fedora/.ssh/authorized_keys
#             chmod 600 /home/fedora/.ssh/authorized_keys
#             chown fedora:fedora -R /home/fedora/.ssh
#             curl -L https://github.com/usrbinkat.keys | tee -a /home/fedora/.ssh/authorized_keys
#             sudo dnf -y install openssh-server qemu-guest-agent @virtualization lnav tmux vi vim
#             sudo systemctl enable --now qemu-guest-agent
#             sudo systemctl enable --now libvirtd
#             sudo systemctl enable --now sshd
#             sudo usermod -aG libvirt fedora
#             sudo dnf -y groupinstall "Container Management"
#             sudo grubby --update-kernel=ALL --args="cgroup_memory=1 cgroup_enable=cpuset cgroup_enable=memory systemd.unified_cgroup_hierarchy=0 intel_iommu=on iommu=pt rd.driver.pre=vfio-pci pci=realloc"
#             sudo echo 'unix_sock_group = "libvirt"' > /etc/libvirt/libvirtd.conf
#             sudo echo 'unix_sock_rw_perms = "0770"' > /etc/libvirt/libvirtd.conf
#             sudo dnf update -y
#             sudo reboot
