---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu-bionic
  namespace: kargo
  labels:
    app: ubuntu
spec:
  running: true
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      domain:
        clock:
          timer: {}
          utc: {}
        cpu:
          sockets: 4
          threads: 1
          cores: 1
          model: host-passthrough
          dedicatedCpuPlacement: false
        resources:
          requests:
            devices.kubevirt.io/kvm: "1"
            memory: 6G
          limits:
            memory: 6G
        machine:
          type: pc-q35-rhel8.4.0
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: containerdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            bootOrder: 2
            bridge: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
      hostname: ubuntu
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containercraft/ubuntu:18.04
            imagePullPolicy: Always
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                eth0:
                  addresses:
                    - 192.168.16.93/24
                  dhcp4: false
                  dhcp6: false
                  gateway4: 192.168.16.1
                  nameservers:
                    addresses:
                    - 192.18.16.1
                    search:
                    - home.arpa
                enp1s0:
                  addresses:
                    - 192.168.16.21/24
                  dhcp4: false
                  dhcp6: false
                  gateway4: 192.168.16.1
                  nameservers:
                    addresses:
                    - 192.18.16.1
                    search:
                    - home.arpa
            userData: |
              #cloud-config
              ssh_pwauth: true
              chpasswd:
                list: |
                   ubuntu:ubuntu
                expire: False
              users:
                - name: ubuntu
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo,docker,xrdp,lxd
                  shell: /bin/bash
              hostname: ubuntu
              runcmd:
                - lxd init --auto
                - apt-get update
                - apt-get install -y screenfetch docker.io
                - echo $(date) > /tmp/complete
