---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu
  namespace: kargo
  labels:
    app: ubuntu
spec:
  running: true
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      domain:
       #clock:
       #  utc: {}
       # #timezone: "America/Los Angeles"
        cpu:
          sockets: 8
          threads: 1
          cores: 1
          dedicatedCpuPlacement: false
          model: host-passthrough
         #model: host-model
        resources:
          requests:
            memory: 16Gi
        machine:
          type: pc-q35-rhel8.2.0
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: containerdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            bootOrder: 2
            bridge: {}
#       features:
#         smm:
#           enabled: true
#       firmware:
#         uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
#         serial: e4686d2c-6e8d-4335-b8fd-81bee22f4815
#         bootloader:
#           efi:
#             secureBoot: true
      hostname: ubuntu
      networks:
      - name: eth0
        multus:
          networkName: br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containercraft/ubuntu:21.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #!/bin/bash -x
              echo 'ubuntu:ubuntu'|chpasswd
              echo 'root:ubuntu'|chpasswd
              mkdir -p /home/ubuntu/.ssh
              touch /home/ubuntu/.ssh/authorized_keys
              curl -L https://github.com/usrbinkat.keys | tee -a /home/ubuntu/.ssh/authorized_keys
              chown ubuntu:ubuntu /home/ubuntu/.ssh
              chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
              chmod 600 /home/ubuntu/.ssh/authorized_keys
              sudo apt-get update -y
              sudo apt-get -y --install-recommends install qemu-guest-agent
              sudo systemctl enable --now qemu-guest-agent
              sudo apt-get -y install cloud-initramfs-growroot openssh-server runc podman tmux vim lnav htop neofetch
              sudo systemctl enable --now sshd
              sudo growpart /dev/vda 1
              sudo apt-get upgrade -y
