---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vyos-wan0-blue-rev01
  namespace: kargo
  labels:
    app: vyos-wan0-blue-rev01
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: vyos-sda-root
      annotations:
        kubevirt.io/provisionOnNode: qotom
    spec:
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      nodeSelector:
        node-role.kubernetes.io/wan: ""
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 11Gi
        storageClassName: hostpath-provisioner
      source:
        registry:
          url: "docker://quay.io/containercraft/vyos:1.4-rolling"
          name: vyos-1.4-rolling
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/wan: ""
      terminationGracePeriodSeconds: 0
      hostname: vyos-wan0-blue-rev01
      domain:
        cpu:
          cores: 2
          threads: 1
          sockets: 1
          dedicatedCpuPlacement: false
          model: host-model
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 2Gi
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          rng: {}
          disks:
            - name: root-disk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
          - name: eth1
            model: virtio
            bridge: {}
          - name: eth2
            model: virtio
            bridge: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-wan0
      - name: eth1
        multus:
          networkName: kargo-net-attach-def-br0
      - name: eth2
        multus:
          networkName: kargo-net-attach-def-dmz0
      volumes:
        - name: root-disk
          dataVolume:
            name: vyos-sda-root
        - name: cloudinitdisk
          cloudInitConfigDrive:
            userData: |
              #cloud-config
              vyos_config_commands:
                - "configure"
                - "set system host-name 'vyos01.qotom.kargo.codectl.lab'"
                - "set system ntp server 1.pool.ntp.org"
                - "set system ntp server 2.pool.ntp.org"
                - "set interfaces ethernet eth1 address '192.168.1.1/16'"
                - "set interfaces ethernet eth0 address 'dhcp'"
                - "set system name-server '1.1.1.1'"
                - "set system name-server '8.8.8.8'"
                - "set system login user vyos authentication public-keys 'vyos' type ssh-rsa"
                - "set system login user vyos authentication public-keys 'vyos' key 'AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U='"
                - "set service ssh listen-address '0.0.0.0'"
                - "set service ssh port '2222'"
                - "commit"
                - "save"
                - "exit"
