---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: test-vyos-wan0
  namespace: kargo
  labels:
    app: vyos-wan0
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: test-vyos-sda-root
      annotations:
        kubevirt.io/provisionOnNode: qotom
    spec:
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 11Gi
        storageClassName: hostpath-provisioner
      source:
        pvc:
          name: vyos-1.3
          namespace: kargo
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      terminationGracePeriodSeconds: 0
      hostname: vyos-wan0
      domain:
        cpu:
          cores: 2
          threads: 1
          sockets: 1
          dedicatedCpuPlacement: false
          model: host-model
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 2Gi
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          rng: {}
          disks:
            - name: root-disk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
          - name: eth1
            model: virtio
            bridge: {}
          - name: eth2
            model: virtio
            bridge: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-wan0
      - name: eth1
        multus:
          networkName: kargo-net-attach-def-br0
      - name: eth2
        multus:
          networkName: kargo-net-attach-def-dmz0
      volumes:
        - name: root-disk
          dataVolume:
            name: test-vyos-sda-root
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              vyos_config_commands:
                - set system host-name 'vyos.kargo.codectl.lab'
                - set system ntp server 1.pool.ntp.org
                - set system ntp server 2.pool.ntp.org
                - set interfaces ethernet eth1 address '192.168.254.1/16'
                - set interfaces ethernet eth0 address dhcp
                - delete interfaces ethernet eth1 address 'dhcp'
#           userData: |-
#             {"ignition":{"version":"3.1.0"},"passwd":{"users":[{"name":"core","passwordHash":"","sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U= kmorgan@mprcs.braincraft.io"]}]}}
