name: Arch
on:
  push:
    paths:
      - 'preview/arch/x86_64/*'
      - '.github/workflows/arch.yml'
#  pull_request:
#    types: [closed]
#    paths:
#      - 'preview/arch/x86_64/*'
#      - '.github/workflows/arch.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex
        sudo apt-get update -y
        sudo apt-get install -y libguestfs-tools

    - name: Code Checkout
      uses: actions/checkout@v2.4.0

    - name: Prepare Arch Image
      run: |
        set -ex
        IMAGE=$(curl -s https://mirror.pkgbuild.com/images/latest/ | grep cloudimg | awk -F\" '{print $2}' | grep -v SHA)
        curl --output /tmp/arch.qcow2 -L https://mirror.pkgbuild.com/images/latest/${IMAGE}
        qemu-img resize /tmp/arch.qcow2 +6G

        virt-sysprep -va /tmp/arch.qcow2 \
          --network \
          --run-command "sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=\"/&console=ttyS0 /' /etc/default/grub" \
          --run-command 'grub-mkconfig -o /boot/grub/grub.cfg' \
          --run-command 'pacman-key --init' \
          --run-command 'pacman-key --populate' \
          --run-command 'pacman --noconfirm -Syu' \
          --run-command 'pacman --noconfirm -S qemu-guest-agent' \
          --run-command 'pacman --noconfirm -S libguestfs' \
          --run-command 'pacman -Scc --noconfirm'

        # virt-sparsify /tmp/arch.qcow2 --compress /tmp/arch.sparse.qcow2 --check-tmpdir ignore

    - name: Build Arch Cradle
      run: |
        ./cradle --image-name quay.io/containercraft/arch --image-tag latest --image-file /tmp/arch.qcow2
        rm -rf /tmp/cradle /tmp/*qcow*

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      # if: github.event.pull_request.merged == true
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Arch Cradle
      # if: github.event.pull_request.merged == true
      run: |
        set -ex
        buildah push quay.io/containercraft/arch:latest
        buildah rmi --all --force
