name: CentOS 8 Streams
on:
  repository_dispatch:
    types:
    - 'centos-8'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y libguestfs-tools ;\
        echo;

    - name: Code Checkout
      uses: actions/checkout@v2.3.5

    - name: Prepare Centos 8 Image
      run: |
        set -ex ;\
        export STREAM=$(curl -L "https://cloud.centos.org/centos/8-stream/x86_64/images/" | grep Generic | awk -F'[=".>< ]' '/x86_64/{print $42}' | awk -F'[-]' '{print $5}' | sort -nr | head -n1) ;\
        curl --output /tmp/centos.qcow2 -L "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-${STREAM}.0.x86_64.qcow2" ;\
        qemu-img resize /tmp/centos.qcow2 +16G ;\
        sudo virt-customize -a /tmp/centos.qcow2 --install 'elrepo-release,epel-release' ;\
        sudo virt-customize -a /tmp/centos.qcow2 --install 'git,vim,htop,tmux,net-tools,qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/centos.qcow2 --run-command "sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config" ;\
        sudo virt-customize -a /tmp/centos.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/centos.qcow2 --run-command "dnf update -y" ;\
        sudo virt-customize -a /tmp/centos.qcow2 --run-command "dnf clean all && rm -rf /var/cache/dnf" ;\
        sudo virt-sysprep -a /tmp/centos.qcow2 --selinux-relabel --password centos:password:centos ;\
        sudo virt-sparsify /tmp/centos.qcow2 --compress /tmp/centos.sparse.qcow2 ;\
        echo;

    - name: Build Centos Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/centos --image-tag 8 --image-file /tmp/centos.sparse.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Centos Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/centos:8 ;\
        podman push quay.io/containercraft/centos:8 docker://quay.io/containercraft/centos:latest ;\
        podman image prune --all --force ;\
        echo;
        
    - name: Cleanup
      run: |
        sudo rm -rf /tmp/cradle /tmp/*qcow*
