name: CentOS 7
on:
  repository_dispatch:
    types:
    - 'centos-7'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y libguestfs-tools ;\
        echo;

    - name: Code Checkout
      uses: actions/checkout@v2.4.0

    - name: Prepare Centos 7 Image
      run: |
        set -ex ;\
        curl --output /tmp/centos.qcow2 -L "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2" ;\
        qemu-img resize /tmp/centos.qcow2 +16G ;\
        sudo virt-sysprep -a /tmp/centos.qcow2 --password centos:password:centos ;\
        sudo virt-customize -a /tmp/centos.qcow2 --install 'tmux,git,vim,net-tools,qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/centos.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/centos.qcow2 --run-command "yum clean all && rm -rf /var/cache/dnf" ;\
        echo;

    - name: Build Centos Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/centos --image-tag 7 --image-file /tmp/centos.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Centos Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/centos:7 ;\
        podman image prune --all --force ;\
        echo;
        
    - name: Cleanup
      run: |
        rm -rf /tmp/cradle /tmp/*qcow*
