name: Fedora 34
on:
  repository_dispatch:
    types:
    - 'fedora-34'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y libguestfs-tools ;\
        echo;

    - name: Code Checkout
      uses: actions/checkout@v2.3.5

    - name: Prepare Fedora 34 Image
      run: |
        set -ex ;\
        curl --output /tmp/fedora.qcow2 -L "https://mirror.arizona.edu/fedora/linux/releases/34/Cloud/x86_64/images/Fedora-Cloud-Base-34-1.2.x86_64.qcow2" ;\
        qemu-img resize /tmp/fedora.qcow2 +16G ;\
        sudo virt-sysprep -a /tmp/fedora.qcow2 --password fedora:password:fedora ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --install 'tmux,git,vim,net-tools,qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command "dnf clean all && rm -rf /var/cache/dnf" ;\
        sudo virt-sysprep -a /tmp/fedora.qcow2 --enable net-hostname,net-hwaddr,machine-id,dhcp-server-state,dhcp-client-state,yum-uuid,udev-persistent-net,tmp-files,smolt-uuid,rpm-db,package-manager-cache
        echo;

    - name: Build Fedora Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/fedora --image-tag 34 --image-file /tmp/fedora.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Fedora Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/fedora:34 ;\
        podman push quay.io/containercraft/fedora:34 docker://quay.io/containercraft/fedora:latest ;\
        podman image prune --all --force ;\
        echo;
        
    - name: Cleanup
      run: |
        rm -rf /tmp/cradle /tmp/*qcow*
