name: Fedora
on:
  push:
    paths:
#     - 'preview/fedora/x64'
      - '.github/workflows/fedora.yml'
  pull_request:
    types: [closed]
    paths:
#     - 'preview/fedora/x64'
      - '.github/workflows/fedora.yml'

jobs:
  build_test_publish:
    # Only run if PR is Closed & Merged
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [34, 35]
        arch: [x86_64]
      fail-fast: false
    env:
      ARCH: ${{ matrix.arch }}
      FLAVOR: fedora
      VERSION: ${{ matrix.version }}
      DOWNLOAD_URL: https://download.fedoraproject.org/pub/fedora/linux/releases/${{ matrix.version }}/Cloud/${{ matrix.arch }}/images/Fedora-Cloud-Base-${{ matrix.version }}-1.2.${{ matrix.arch }}.qcow2

    steps:
    - name: Install Dependencies
      run: |
        set -ex
        sudo apt-get update -y
        sudo apt-get install -y libguestfs-tools

    - name: Code Checkout
      uses: actions/checkout@v2.4.0

    - name: Download & Prepare Fedora ${{ matrix.version }} ${{ matrix.arch }} Cloud Image
      run: |
        set -ex
        curl --output /tmp/${FLAVOR}.qcow2 -L "${DOWNLOAD_URL}"
        qemu-img resize /tmp/${FLAVOR}.qcow2 +19G
        sudo virt-sparsify /tmp/${FLAVOR}.qcow2 --compress /tmp/${FLAVOR}.sparse.qcow2
        sudo mv -f /tmp/${FLAVOR}.sparse.qcow2 /tmp/${FLAVOR}.qcow2
        sudo qemu-img info /tmp/${FLAVOR}.qcow2

    - name: Build kc2 Fedora ${{ matrix.version }} ${{ matrix.arch }} Image
      run: |
        set -ex
        df -h /
        sudo virt-sysprep -va /tmp/${FLAVOR}.qcow2 \
          --enable user-account,logfiles,customize,bash-history,net-hostname,net-hwaddr,machine-id,dhcp-server-state,dhcp-client-state,yum-uuid,udev-persistent-net,tmp-files,smolt-uuid,rpm-db,package-manager-cache \
          --update \
          --network \
          --install tmux,git,vim,net-tools,qemu-guest-agent             \
          --run-command 'systemctl enable qemu-guest-agent'             \
          --run-command 'dnf clean all'                                 \
          --run-command 'rm -rf /var/cache/dnf'                         \
          --selinux-relabel                                             ;
        sudo virt-sparsify -v /tmp/${FLAVOR}.qcow2 --compress /tmp/${FLAVOR}.sparse.qcow2

    - name: Build kc2 Fedora Cradle
      run: |
        set -ex
        sudo qemu-img info /tmp/${FLAVOR}.sparse.qcow2
        ./cradle --image-name quay.io/containercraft/${FLAVOR} --image-tag ${VERSION} --image-file /tmp/${FLAVOR}.sparse.qcow2
        sudo rm -rf /tmp/cradle /tmp/*qcow*

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push kc2 Fedora ${{ matrix.version }} ${{ matrix.arch }} Cradle
      run: |
        set -ex
        buildah images quay.io/containercraft/${FLAVOR}:${VERSION}
        buildah push quay.io/containercraft/${FLAVOR}:${VERSION}
        buildah rmi --all --force
