name: Workflow Dispatcher
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y \
            libguestfs-tools \
        ;echo;

    - name: Code Checkout
      uses: actions/checkout@v2.3.4

    - name: Prepare Debian Image
      run: |
        set -ex ;\
        curl --output /tmp/debian.qcow2 -L "https://cdimage.debian.org/images/cloud/OpenStack/current-9/debian-9-openstack-amd64.qcow2" ;\
        qemu-img resize /tmp/debian.qcow2 +48G ;\
        sudo virt-sysprep -a /tmp/debian.qcow2 --password debian:password:debian ;\
        sudo virt-customize -a /tmp/debian.qcow2 --install 'curl,tmux,git,vim,net-tools,qemu-guest-agent,cloud-init,cloud-initramfs-growroot' ;\
        sudo virt-customize -a /tmp/debian.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/debian.qcow2 --update ;\
        echo;

    - name: Build Debian Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/debian --image-tag 9 --image-file /tmp/debian.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Debian Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/debian:9 ;\
        podman push docker://quay.io/containercraft/debian:9 docker://quay.io/containercraft/debian:latest ;\
        echo;

    - name: Prepare Debian Image
      run: |
        set -ex ;\
        curl --output /tmp/debian.qcow2 -L "https://cdimage.debian.org/images/cloud/OpenStack/current-10/debian-10-openstack-amd64.qcow2" ;\
        qemu-img resize /tmp/debian.qcow2 +48G ;\
        sudo virt-sysprep -a /tmp/debian.qcow2 --password debian:password:debian ;\
        sudo virt-customize -a /tmp/debian.qcow2 --install 'curl,tmux,git,vim,net-tools,qemu-guest-agent,cloud-init,cloud-initramfs-growroot' ;\
        sudo virt-customize -a /tmp/debian.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/debian.qcow2 --update ;\
        echo;

    - name: Build Debian Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/debian --image-tag 10 --image-file /tmp/debian.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Debian Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/debian:10 ;\
        podman push docker://quay.io/containercraft/debian:10 docker://quay.io/containercraft/debian:latest ;\
        echo;

    - name: Prepare Ubuntu Image
      run: |
        set -ex ;\
        curl --output /tmp/ubuntu.qcow2 -L "https://cloud-images.ubuntu.com/releases/hirsute/release/ubuntu-21.04-server-cloudimg-amd64-disk-kvm.img" ;\
        qemu-img resize /tmp/ubuntu.qcow2 +48G ;\
        sudo virt-sysprep -a /tmp/ubuntu.qcow2 --password ubuntu:password:ubuntu ;\
        sudo virt-customize -a /tmp/ubuntu.qcow2 --install 'tmux,git,vim,net-tools,qemu-guest-agent,cloud-init,cloud-initramfs-growroot' ;\
        sudo virt-customize -a /tmp/ubuntu.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/ubuntu.qcow2 --update ;\
        echo;

    - name: Build Ubuntu Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/ubuntu --image-tag 21.04 --image-file /tmp/ubuntu.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Ubuntu Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/ubuntu:21.04 ;\
        podman push docker://quay.io/containercraft/ubuntu:21.04 docker://quay.io/containercraft/ubuntu:latest ;\
        echo;
        
    - name: Cleanup
      run: |
        rm -rf /tmp/cradle /tmp/*qcow*

    - name: Prepare Fedora Image
      run: |
        set -ex ;\
        curl --output /tmp/fedora.qcow2 -L "https://download.fedoraproject.org/pub/fedora/linux/releases/34/Cloud/x86_64/images/Fedora-Cloud-Base-34-1.2.x86_64.qcow2" ;\
        qemu-img resize /tmp/fedora.qcow2 +22G ;\
        sudo virt-sysprep -a /tmp/fedora.qcow2 --password fedora:password:fedora ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --install 'tmux,git,vim,net-tools,qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --update ;\
        echo;

        #sudo virt-customize -a /tmp/fedora.qcow2 --run-command "dnf update -y" ;\
        #sudo virt-customize -a /tmp/fedora.qcow2 --run-command "dnf upgrade -y" ;\
        #sudo virt-customize -a /tmp/fedora.qcow2 --run-command "dnf clean all && rm -rf /var/cache/dnf" ;\
        #sudo virt-customize -a /tmp/fedora.qcow2 --run-command "grubby --update-kernel=ALL --args 'cgroup_memory=1 cgroup_enable=cpuset cgroup_enable=memory systemd.unified_cgroup_hierarchy=0 intel_iommu=on iommu=pt rd.driver.pre=vfio-pci pci=realloc'" ;\

    - name: Build Fedora Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/fedora --image-tag 34 --image-file /tmp/fedora.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Fedora Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/fedora:34 ;\
        podman push docker://quay.io/containercraft/fedora:34 docker://quay.io/containercraft/fedora:latest ;\
        echo;
        
    - name: Cleanup
      run: |
        rm -rf /tmp/cradle /tmp/*qcow*
