name: Workflow Dispatcher
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y \
            libguestfs-tools \
        ;echo;

    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Login Quay.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Prepare Fedora Image
      run: |
        set -ex ;\
        curl --output /tmp/fedora.qcow2 -L "https://download.fedoraproject.org/pub/fedora/linux/releases/34/Cloud/x86_64/images/Fedora-Cloud-Base-34-1.2.x86_64.qcow2" ;\
        qemu-img resize /tmp/fedora.qcow2 +22G ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command "dnf update -y && dnf upgrade -y"
        sudo virt-customize -a /tmp/fedora.qcow2 --install 'tmux,git,vim,net-tools,qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command "dnf clean all && rm -rf /var/cache/dnf"
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/fedora.qcow2 --run-command "grubby --update-kernel=ALL --args 'cgroup_memory=1 cgroup_enable=cpuset cgroup_enable=memory systemd.unified_cgroup_hierarchy=0 intel_iommu=on iommu=pt rd.driver.pre=vfio-pci pci=realloc'" ;\
        echo;

    - name: Build Fedora Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/fedora --image-tag 34 --image-file /tmp/fedora.qcow2 ;\
        echo;

    - name: Push Fedora Cradle
      run: |
        podman push quay.io/containercraft/fedora:34
        
    - name: Cleanup
      run: |
        rm -rf /tmp/cradle /tmp/*qcow*
