name: Ubuntu 18.04 Bionic Bever
on:
  repository_dispatch:
    types:
    - 'ubuntu-1804'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Install Dependencies
      run: |
        set -ex ;\
        sudo apt-get update -y ;\
        sudo apt-get install -y libguestfs-tools ;\
        echo;

    - name: Code Checkout
      uses: actions/checkout@v2.4.0

    - name: Prepare Ubuntu Bionic Beaver 18.04 Image
      run: |
        set -ex ;\
        curl --output /tmp/ubuntu.qcow2 -L "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img" ;\
        qemu-img resize /tmp/ubuntu.qcow2 +48G ;\
        sudo virt-sysprep -a /tmp/ubuntu.qcow2 --password ubuntu:password:ubuntu ;\
        sudo virt-customize -a /tmp/ubuntu.qcow2 --install 'ansible,python,tmux,git,vim,net-tools,qemu-guest-agent,cloud-init,cloud-initramfs-growroot' ;\
        sudo virt-customize -a /tmp/ubuntu.qcow2 --run-command 'systemctl enable qemu-guest-agent' ;\
        sudo virt-customize -a /tmp/ubuntu.qcow2 --update ;\
        echo;

    - name: Build Ubuntu Cradle
      run: |
        PATH=${PATH}:$(pwd) \
        cradle --image-name quay.io/containercraft/ubuntu --image-tag 18.04 --image-file /tmp/ubuntu.qcow2 ;\
        echo;

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Push Ubuntu Cradle
      run: |
        set -ex ;\
        podman push quay.io/containercraft/ubuntu:18.04 ;\
        podman push quay.io/containercraft/ubuntu:18.04 docker://quay.io/containercraft/ubuntu:bionic ;\
        podman image prune --all --force ;\
        echo;
